### ISSUE TITLE
Feature: 为每条回复消息添加自定义 footer

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi-plugin-github#10]
类似「此回复由 koishi-plugin-github 发送。」

**Comment by Dragon-Fish** [comment]
希望做成可选功能

**Comment by shigma** [comment]
为了不影响现有用户，此功能将会通过配置项控制并且默认不开启。

**Comment by shigma** [comment]
test

---
Generated by [koishi-plugin-github](https://github.koishi.chat/)

**Comment by Dragon-Fish** [comment]
我看到有一些 GitHub App 在使用留言功能时，头像那里会显示一个应用程序角标，不知道 koishi 能否采用这种做法，更加 native & elegant

例如utterances
![图片](https://user-images.githubusercontent.com/44761872/196007230-1a4cc254-88a6-4b51-a5a3-a9e7a9740116.png)
