### ISSUE TITLE
Feature: check username when prompted to log in

### ISSUE THREAD

**Issue by shigma** [koishijs/koishi-plugin-github#6]
If it is not a valid username then don't send the link.

> Username may only contain alphanumeric characters or single hyphens, and cannot begin or end with a hyphen.

**Comment by Seidko** [comment]
请问我可以参加这个功能的开发吗

**Comment by HuanLinMaster** [comment]
有没有一种可能 你可以直接pr

**Comment by shigma** [comment]
> 请问我可以参加这个功能的开发吗

Surely you can.

**Comment by shigma** [comment]
但如果群友一直起哄的话我可能忍不住抢先一步做了，所以你需要制止一下群友的行为。

**Comment by Seidko** [comment]
> 有没有一种可能 你可以直接pr

开发过程中的协商是很重要的……如果你辛辛苦苦做了半天发了个pr，发现别人都已经做好了，那岂不是很苦恼？

再者，开发并不是一个一蹴而就的事情，直接发pr并不现实，虽然可以设置为WIP，但我个人认为pr应该在一个功能相对完善以后再发出。

最后，”有没有一种可能“这个句式有时候很伤人，请你也在提出意见的时候适当的调节一下你的用词。
