### ISSUE TITLE
Question: Is the name input step of authorization really necessary?

### ISSUE THREAD

**Issue by MicroCBer** [koishijs/koishi-plugin-github#7]
According to gh oauth docs, the `login` argument is not required, also there seems to be no influence to remove this argument, the `login` argument seems to be unnecessary so that we won't have to ask the user to input his username when authorizing.

![_LFGAEQAH W3 }P89Z2HNC9](https://user-images.githubusercontent.com/66859419/195903794-07a8db6a-a39b-4c58-81e7-0881dfb8d29c.png)
![}B1`DP4N6RNT0 `QC4N%GPJ](https://user-images.githubusercontent.com/66859419/195903777-6cfbaccb-3a2e-494e-93bc-6c9d0af2d23a.png)
![FA085{IOY5VP6AL1H57KHJO](https://user-images.githubusercontent.com/66859419/195903782-6a9dcc76-afe1-4489-aa53-e9e9a79c765c.png)

**Comment by MicroCBer** [comment]
test

**Comment by MicroCBer** [comment]
#18

**Comment by shigma** [comment]
草，我甚至没见过这个 issue

**Comment by MicroCBer** [comment]
> 草，我甚至没见过这个 issue

~~我发英文梦梦回中文 我发中文梦梦回英文~~
